Some Patches + Documentation
kanjieater/anki-plugin-heisigs-rtk pull request #2
Opened 2022-12-21 14:12 UTC by Nayelianne

- Created config.md
- Did some changes on the rtkkw.py to facilitate user styling + a (presumed) bug fix.
- Created Readme.md
- Added bunch of example images
- Fixed social icons that were wonky on the goldendict addon github page
- modified config.json to include the new separator thingy + better reflect the recommended deck defaults
- modified init file to add a little separator on the context menu so it doesn't blend with other addons

I've added comments to the commits if helps understand what was changed. The update on the readme was a bit of a rush job from the previous one I had done, since I saw the add-on already got updated on Ankiweb, so might be good to double check if I didn't miss anything super important though.

2022-12-24 21:10 UTC, kanjieater commented
This looks great. If you could address the items I commented on with a counter-point or resolution, I'll merge this when we're both satisfied. Thanks again! 👍

2022-12-25 21:50 UTC, Nayelianne commented
@kanjieater Sorry to be a potato, I'm new to github, but where can I find your comments?

2022-12-26 04:13 UTC, kanjieater requested changes

2022-12-26 04:13 UTC, kanjieater commented on config.json
> +    "kanjiUrl": "https://kanji.koohii.com/study/kanji/",
This link doesn't work anymore, so we should keep it as jisho I think

2022-12-26 04:13 UTC, kanjieater commented on config.json
> +    "rtkModel": "Japanese Heisigs RTK all-in-one",
I'd prefer to update the other fields as well to keep them simpler.

EDIT: We can ignore this comment. It's fine. Forgot we linked to the deck that's still out there on anki web, so it's simpler to keep as is.

2022-12-26 04:13 UTC, kanjieater commented on config.md
> +**"vocabUrl":**  If you used KanjiVocab, this is where all the vocab words in your Destination field will link to (in a single link). Eg. If the Vocab is x漢字 and 練習 it will link to "https://jisho.org
I think the link in this line probably needs to `[text to show for url](actual url)` to link properly

2022-12-26 04:14 UTC, kanjieater commented
Seems it was my fault as github showed them to me but I had to submit them. You should be able to see them now

2022-12-26 04:16 UTC, Nayelianne commented on config.json
> +    "kanjiUrl": "https://kanji.koohii.com/study/kanji/",
What do you mean it doesn't work anymore? It's working fine here (after I messed with the rttkw file) o_o

2022-12-26 04:18 UTC, Nayelianne commented on config.json
> +    "rtkModel": "Japanese Heisigs RTK all-in-one",
Hahah yeah, I just used the name on the ankiweb deck since it's the one you recommended on the addon page

2022-12-26 04:23 UTC, Nayelianne commented on config.json
> +    "kanjiUrl": "https://kanji.koohii.com/study/kanji/",
![Proof](https://i.imgur.com/ALaLCPY.gif)

2022-12-26 04:25 UTC, Nayelianne commented on config.md
> +**"vocabUrl":**  If you used KanjiVocab, this is where all the vocab words in your Destination field will link to (in a single link). Eg. If the Vocab is x漢字 and 練習 it will link to "https://jisho.org
Oh, true, I wasn't thinking of it being a link when I wrote it haha, I'll fix it

2022-12-29 00:42 UTC, kanjieater commented
Sorry for the delay, I'm going to check this out again this weekend and make sure everything is working, then merge, then deploy it to anki web. Thanks for the patience.

2022-12-31 19:11 UTC, kanjieater approved these changes

2022-12-31 19:12 UTC, merged